meta.go, meta_test.go, screwdriver.yaml
This PR provides interface of the meta-cli.
I wrote `screwdriver.yaml` and `meta.go` based on [launcher](https://github.com/screwdriver-cd/launcher).
The help message of meta-cli is following:
```
% go build -o meta                                                                                                                 
% ./meta                                                                                                                           
NAME:
meta-cli - get or set metadata for Screwdriver build
USAGE:
meta command arguments [options]
VERSION:
0.0.0
COMMANDS:
get      Get a metadata with key
set      Set a metadata with key and value
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--meta-space value  Location for saving meta temporarily …
```
=> feat: first step for implementing meta-cli

.gitignore, meta.go, meta_test.go, mock/meta.json
To enable to pass the data between build in the same event, `meta-cli` provides simple interface for reading/writing values as command line client.
This `meta-cli` is called in build container and save meta to temporary file.
Before finish the build, this meta put to data store via API call.
This stored meta will be loaded when setup next build.
Detail is https://github.com/screwdriver-cd/screwdriver/issues/293.
Based on https://github.com/screwdriver-cd/screwdriver/issues/293, this PR provides meta-cli implementation.
"Stretch (gold bar): ..." is not implemented this PR yet.
This works like following:
```
$ go build
$ ./meta-cli set foo[2].bar[1] baz
$ ./meta-cli get foo
[null,null,{"bar":[null,"baz"]}]
```
I think this meta-cli is called in …
=> feat: implement meta-cli and test

meta.go, meta_test.go, mock/meta.json
`meta get` could not get nested value like following:
```
sh-3.2$ ./meta set foo.bar baz
sh-3.2$ ./meta get foo && echo
{"bar":"baz"}
sh-3.2$ ./meta get foo.bar && echo
null
```
I fixed to enable to get such value like following:
```
$ ./meta set foo.bar baz                                                                                                                                           
$ ./meta get foo                                                                                                                                                   
{"bar":"baz"}%         
$ ./meta get foo.bar …
```
=> fix(293): meta get enable to get map and array meta

meta.go, meta_test.go
This PR provides:
- Renamed variables and function to more meaningful.
- Separated some function (e.g. type conversion function).
- Added comments.
- Fixed `meta set` logic.
- When `[x]` comes after `.`, meta-cli updates array but destruct previous meta. This PR fixed this bug.
Related: https://github.com/screwdriver-cd/screwdriver/issues/293#issuecomment-286246365
=> fix(293): Refactoring and fix metaSet logic

.gitignore, meta.go, meta_test.go
When trying to add in a new key, the object gets overridden. This happened like below:
```
shared:
image: node:6
jobs:
main:
steps:
- test: meta set foo.a true
- test1: meta set foo.b true
- test3: echo `meta get foo`
```
The actual output of the echo is `"{ "b" : true }"`, and the expected output would be `"{ "a": true, "b": true}"`
Also, when trying to update array-object meta, the array is overwritten.
```
% meta set foo[0].bar[1] aaa
% meta set foo[0].bar[0] bbb
% meta get foo[0]
{"bar":["bbb"]}
```
The expected output would be `{"bar":["bbb", "aaa"]}`.
Fixed these bug and added test for these pattern.
`% go test` is passed and the above example is also worked.
First commit fixed array-object bug, second commit fixed object overwrite bug.
```
% ./meta-cli set foo.a true 
% ./meta-cli …
```
=> fix(543): fix to not overwrite object and fix array-object meta

.gitignore, .goreleaser.yml, screwdriver.yaml
We'd like to build iOS apps in MacOS VMs.
Build and release for 64-bit macos. This PR uses goreleaser, see https://github.com/screwdriver-cd/log-service/pull/12 .
I have created related PRs to sd-steps,  log-service, meta-cli, launcher. Please merge them at the same time, because the Dockerfile of launcher depends on the filname uploaded to GitHub Release.
Use jenkins executor for macos node : https://github.com/screwdriver-cd/executor-j5s/pull/12
=> feat: Build darwin/amd64 binary

screwdriver.yaml
Use toolbox repo instead of personal gist
Related to https://github.com/screwdriver-cd/screwdriver/issues/729
=> fix: use toolbox repo instead of gist

meta.go, meta_test.go
So `meta get foo --external sd@123:component` is not working in `beta`.
I went inside the container and the file `sd@123:component.json` is actually there. However, it's not able to read it because the flag doesn't include `json`. We need to add it. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/771
=> fix: metaFile does not include json

meta.go, meta_test.go
Users should only be able to `meta get` from external builds. If they try to `meta set` an external build, the build should fail.
This PR checks if the file that we are trying to `meta set` is the current build meta or not.
https://github.com/screwdriver-cd/screwdriver/issues/771
=> fix: Can only meta set current running build meta

meta.go, meta_test.go, mock/meta.json
When we do meta get a number >6 digits, it will convert to +e06
For example,
```
$ meta set build_version_1 1234567
$ meta get build_version_1`
1.234567e+06
```
A meta value is converted to float64 from interface in spite of an integer is load from a json file. It seems to be specification of json.Unmarshal().
We use "Decoder" instead of json.Unmarshal(). "Decoder" has [UseNumber() function](https://golang.org/src/encoding/json/stream.go?s=800:831#L26). It works as following:
> UseNumber causes the Decoder to unmarshal a number into an interface{} as a Number instead of as a float64.
Test is also modified.
Reference: https://github.com/golang/go/issues/5562
Related: https://github.com/screwdriver-cd/screwdriver/issues/839
=> fix(839): use Decoder instead of json.Unmarshal

habitat/plan.sh
I forgot to include this in the dependency list.  See failed build here: https://bldr.habitat.sh/#/pkgs/screwdriver-cd/meta-cli/builds/911133979712364544
=> fix(habitat): Download the right dependencies

meta.go, meta_test.go
This fixes screwdriver-cd/screwdriver#1193.
The cause of the issue is writing empty string to `meta.json` if there is no `meta.json` yet, so writing an empty object `{}` resolves this issue.
=> fix: JSON unmarshall error

screwdriver.yaml
PR replaces no longer needed / redundant `go get ./...` invocation with a new `modverify` step running `go mod verify`.  It also simplifies the `gofmt` command in the corresponding step: it is useless to format the data (with `-w` flag) in the build since formatting is for humans, the compiler doesn't care much about whitespaces and so on 😄 On the other hand, I believe we should fail the build if the contributor hasn't done the proper formatting of the modified code.
@tk3fftk 
=> replace 'go get' with 'go mod verify'

README.md, go.mod, go.sum, meta.go, meta_test.go
There are times when it's desirable to do a deep copy of metadata - for instance, when a scheduled job wants to get the lastSuccessfulMeta of a component job and copy it in so that jobs triggered off it have meta associated with the event (and can be re-run without taking another snapshot).
Adds a flag -j or --json-value for get and set that treats the input string as a json-formatted string.
=> Allow json values in get/set.

meta_test.go
A comment was made to #20 asking for a test of the error case; in addition, the intention of the `--json-value` flag as applied in the get command is to remain "symmetric" (`meta get -j foo` should be the same before and after `meta set -j foo "$(meta get -j foo)"`; so write a test to ensure that intention.
No fixes; only tests
#20 
=> Add tests for symmetry with set/get using -j flag; also add test of error as requested in #20

README.md, meta.go
If options _were_ passed in the global spot (before the command) then they were overwritten by the commands' flag parsing (default value).
Competes with #25 and I believe is superior as it is closer to backward-compatible with existing jobs. The only incompatibility will be for any jobs using the `--meta-space` flag, that will now need to put that before the command as the `urfave/cli` library seems to demand global options before commands (unlike spf13/cobra which allows mixing of flags)
```
meta get foo --meta-space "$PWD/meta" --external sd@123:other-job
```
would need to be
```
meta --meta-space "$PWD/meta" get foo --external sd@123:other-job
```
the CLI library used has the notion of global and per-command flags.  The code currently puts the flags in both positions.  This means that …
=> Ensure global options and command options are not duplicated

meta.go
#26 reduced the number of global flags; variables now need default settings for the case where they're not defaulted with the flags mechanism.  Specifically, `meta set foo bar` fails with `ERROR: can only meta set current build meta` currently.
`ERROR: can only meta set current build meta`
#26 
=> Set the default of metaFile to "meta".

meta.go
Recently someone asked why `meta get --external sd@12345:jobName --skip-fetch true theKey` didn't work - and it was because `true` was _not_ passed to `--skip-fetch`, which is a bool flag (absent is false, present is true) so true was passed as the first arg and the second arg (intended to be the key) was just ignored.
Report errors when extraneous args are passed.
=> Error when extra args are passed.

internal/fetch/jobDescription.go, internal/fetch/jobDescription_test.go
JobName parsing fails because `-` throws the regular-expression off.
Allow `--external` to have jobNames with dashes in them.
=> JobName can have dashes in it

meta.go, meta_test.go
When `--skip-meta` flag is passed, empty external metadata (`{}`) should not be stored in default meta.
```
meta get foo --external sd@123:other --skip-fetch
meta get foo --external sd@123:other
```
=> --skip-meta shouldn't cache in default meta.

internal/fetch/jobDescription.go, internal/fetch/jobDescription_test.go, meta.go
If users invoke like ```meta get --external --skip-fetch sd@123:main theKey``` it would be better to explain that `--skip-fetch` was being passed to `--external` to help self-diagnose.
=> Check for passing flags to --external by looking for jobName starting with dash

go.mod, go.sum, internal/fetch/jobDescription.go, internal/fetch/lastSuccessfulMeta.go, internal/fetch/lastSuccessfulMeta_test.go, meta.go, meta_test.go
if meta set is invoked multiple times in parallel, corruption of the underlying json file(s) can occur.
Using flock, ensure that both get and set obtain an exclusive (aka "write") lock (we could make it more granular, but get does the fetching logic now, so might do writes).
https://github.com/gofrs/flock
=> Make meta concurrency-safe using flock

meta.go, meta_test.go
It can be confusing to see an external meta file with `{}` in it but a meta.json with the fully fetched external metadata.  Taking the stance of leaving the external file readonly, don't create an empty json object when the file doesn't exist.
=> Do not write the external file if it didn't exist.

screwdriver.yaml
PR adds a step to display the Go version we are using.
=> display go version

README.md, meta.go, meta_test.go, mock/sd@123:component.json
This is to handle the case where a scheduled job wishes to trigger the rest of a pipeline as if it were triggered from the component job. If the component writes fields underneath `mycomponentmeta` such as `meta set mycomponentmeta.foo bar` The scheduled job can simply do the following:
```
meta get mycomponentmeta -j --external component --cache-local &> /dev/null
```
And downstream jobs will pick up as if they were downstream of the component job because  `mycomponentmeta` will be filled in.
When `--cache-local` and `--external` flags are used:
1. Check local meta and return if non-null
1. Process external get as usual with local file or fetching
1. Store the return value into the key in local meta.
I confirm that this contribution is made under the terms of the license found in the …
=> Add --cache-local flag to fetch external keys to remote meta

meta.go, meta_test.go, mock/job-params-component-pr-build.json
With changes made in https://github.com/screwdriver-cd/models/pull/521, 
the job level parameters are always stored under original/parent job name in `meta` .
To lookup job level parameters in `meta`, we should use original/parent job name (Ex: `component`) instead of build job name (Ex: `PR-3:component`).
https://github.com/screwdriver-cd/screwdriver/issues/2346
https://github.com/screwdriver-cd/models/pull/521
https://github.com/screwdriver-cd/meta-cli/pull/46
=> fix(2346): For PR build, lookup job level parameters using parent job name

go.mod, go.sum
In order to convert parameters to shell environment a la ENV_VAR='some value', pull in the latest gopher-lua-libs to get shellescape.
Use-case is to convert params into source-able shell script that looks something like the following, with values properly escaped:
```bash
SOME_KEY='some value'
```
Pulls in the version of gopher-lua-libs with [shellescape](https://github.com/alessio/shellescape) support.
https://github.com/vadv/gopher-lua-libs/pull/23
=> Pull in latest gopher-lua-libs to get shellescape module

screwdriver.yaml
goreleaser fails currently even with the last good build; try reverting to an older version that was available at the time of the last good build
Fix the broken build <https://cd.screwdriver.cd/pipelines/67/builds/783080/steps/release> 
=> Try older version of goreleaser to see if it unsticks us.

meta.go, screwdriver.yaml, test-shebang.lua
- Making larger meta commands, such as loading from json file or yaml file, can be possible with lua.
- The current mechanism for commands, requires a single file to be used for binary commands.
- Having lua code in a file suffixed with `.lua` helps most editors/IDEs to write more easily.
Therefore, it would be really nice to be able to have sd commands be written like:
```lua
#!/usr/bin/env meta
print("hello world")
```
- Be able to run sd commands as meta lua with shebang `#!/usr/bin/env meta`
Previously, I had tried writing commands using `env -S` but that's only available in "BSD" forks of unix like mac; not on most linux images.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the …
=> Allow meta to be used in shebang for lua scripting.

.goreleaser.yml
M1 macs are arm64, and some arm nodes in public cloud may be cheaper… if building is as easy as requesting it of the goreleaser, then just do that
Make arm64 versions for mac and linux.
=> Build for arm64 as well.

meta.go
The previous commit #59 worked because "null" typically didn't match any real jobnames, but, if we use the lower-level `fetchMetaValue` method, we can tell the difference between `nil` the missing value and `"null"` the string value.
Small cleanup to just check that the build.jobName is set before looking it up in the original `parameters`
=> Just ensure that the jobName exists (before it was looking up "null").

go.mod, go.sum
[This PR](https://github.com/vadv/gopher-lua-libs/pull/31) in the lua libs added lua support for Base64, which can be useful for slurping in binary files to meta values as base64 strings.
Furthermore, that PR added file I/O for base64, json and yaml via the Encoder/Decoder pattern for things to go straight to/from file to the right representation without going through string first.
There are some use-cases that desire putting json/yaml files or small binary files in meta keys for reference or downstream communication. Being able to go straight from file to meta (or vice versa) helps avoid CLI escaping in the process.
This change upgrades to the latest release to get these features in meta.
- Add support for Base64, and file I/O encoder/decoder to json/yaml.
- …
=> Upgrade gopher-lua-libs for base64 support (and json/yaml file-io encoder/decoder).

.gitignore, .goreleaser.yml
In order to install `meta` locally, generate a homebrew Formula during goreleaser release
- Create a homebrew formula, which can be tapped and installed to get `brew` on a laptop.
- https://goreleaser.com/customization/homebrew/?h=homebrew
=> Add brew generation to goreleaser config

meta.go
Currently, meta-cli exit without fail if the number of arguments is invalid.
It should exit with fail if the number of arguments is invalid.
Exit with fail if the number of arguments is invalid.
=> fix: Exit with fail if the number of arguments is invalid

lua_test.go, testdata/test.lua
The latest gopher-lua-libs also adds test `suite.Suite` and `testing.T.TempDir` making it possible to reduce hand-crafted infra here for invoking the tests - the `test.lua` can just have the suite subclass with SetupTest method to assign the `MetaSpace` to a `TempDir` so it's "fresh" for every test.
Uses https://github.com/vadv/gopher-lua-libs test infra for invoking tests written in lua from go
- https://github.com/vadv/gopher-lua-libs/pull/51
=> Use the tests helpers from gopher-lua-libs and its suite lua class.

lua.go, lua_test.go
```bash
$ meta set -j foo {}
$ meta get foo | jq .
{}
$ meta lua -E 'meta.set("foo", meta.get("foo"))'
$ meta get foo | jq .
[]
```
In lua, tables are actually "associative arrays" - used for both slices and maps (See [Values and Types](https://www.lua.org/manual/5.1/manual.html#2.2)).
An empty table is ambiguous for whether that should represent json `[]` or `{}`.  The gopher-lua-libs json lib sets a metatable to mark a table as coming from an object when decoding, and, when encoding, checks this marshaling empty values to distinguish between array and map.
=> Ensure that json is not just preloaded but actually loaded so that, when using its methods, it is able to use registered types.
